spring:
  application:
    name: ead-course-service
  config: #Configuração de conexão com o Config Server
    import: 'optional:configserver:' #O optional:, define que caso o config server não esteja disponível, será utilizado as configurações desse arquivo.
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
      password: 'ead123cs'
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course-v2
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://asepknsw:AkZI1YjGQhqp8qSAFcm56tHkiXyiOjiE@shark.rmq.cloudamqp.com/asepknsw #Endereço do rabbitMq para comunicação com a instancia do Broker.
#
#
#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'
#
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#      notificationCommandExchange: ead.notificationcommand
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#    key:
#      notificationCommandKey: ms.notification
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - refresh
#          - health
#
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://localhost:8761/eureka'
#    instance:
#      hostname: localhost